# -*- coding: utf-8 -*-
"""Titorial 05. Velocidade Terminal de unha partícula no seo dun fluído Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bPTRhZhbePS6SsquqHh1nSPlrZMnzbzb

## Velocidade terminal de partículas descendentes
### Cálculo da velocidade de caída de partículas no seo de fluidos baixo a acción da forza da gravedade.
  
Un balance simple de forzas sobre unha partícula esférica que acada a súa velocidade terminal de caída no seo dun fluido ven dada por:
  
$$
v_t = \sqrt{ \frac {4g \left ( \rho_p - \rho \right ) D_p} {3 C_D \rho} }
$$
  
onde:  
$v_t$ é a velocidade terminal de caída en $m \cdot s^{-1}$  
$g$ é a aceleración da gravedade dada por $g = 9,80665 m \cdot s^{-2}$  
$\rho_p$ é a densidade da partícula en $kg \cdot m^{-3}$  
$\rho$ é a densidade do fluído en $kg \cdot m^{-3}$  
$D_p$ é o diámetro da partícula esférica en $m$  
$C_D$ é un coeficinte de rozamento adimensional.
  
O coeficinte de rozamiento dunha partícula esférica á súa velocidade terminal varía co número de __Reynolds (Re)__ do xeito seguinte:  
$$
C_D = \frac {24} {Re} \; para \: Re < 0.1
$$
 
$$
C_D = \frac {24} {Re} \left ( 1 + 0.14 \cdot Re^{0.7} \right ) \; para \: 0.1 \leq Re \leq 1000
$$
  
$$
C_D = 0.44 \; para \: 1000 < Re \leq 35000
$$
  
$$
C_D = 0.19 - \frac {8 \cdot 10^4} {Re} \; para \: 1000 < Re \leq 350000
$$

onde:
  
$$
Re = \frac {D_P v_t \rho} {\mu}
$$
3 $\mu$ é a viscosidade expresada en $Pa \cdot s$ ou $kg \cdot m \cdot s^{-1}$.

1. Calcula-la velocidade terminal de partículas de carbón con $\rho_p$ = 1800 $kg \cdot m^{-3}$ e $D_p$ = $0.208 \cdot 10^{-3} \; m$ caendo en auga a $T$ = 298.15 $K$ onde $\rho$ = 994.6 $kg \cdot m^{-3}$ e $\mu$ = $8.931 \cdot 10^{-4} \; kg \cdot m \cdot s$.  
2.	Estima-la velocidade de caída terminal das partículas de carbón en auga dentro dun separador centrífugo no que a aceleración é de 30 $g$.
"""

from scipy import *
from scipy.optimize import fsolve

# Constantes

rho_p = 1800.0      # kg/m3
rho   = 994.6       # kg/m3
D_p   = 0.208e-3    # m
mu    = 8.9311e-4   # kg/ms
g     = 9.80665     # m/s2

def velocidade_terminal(vt):
    Re_vt = D_p * vt * rho / mu
    if Re_vt < 0.1:
        C_D = 24 / Re_vt
    else:
        C_D = (24.0 * ( 1.0 + 0.14 * Re_vt ** 0.7 ) / Re_vt) 
    return vt ** 2 * ( 3.0 * C_D * rho ) - 4 * g * ( rho_p - rho ) * D_p

# Apartado 1
v_t = fsolve(velocidade_terminal, 0.01)
print('Reynolds =', D_p * v_t * rho / mu)
print('Velocidade terminal da partícula =', v_t, 'm/s')

# Apartado 2
g = 30 * g
v_t = fsolve(velocidade_terminal, 0.01)
print('Reynolds =', D_p * v_t * rho / mu)
print('Velocidade terminal da partícula =', v_t, 'm/s')